# Generated by Django 5.0.4 on 2024-04-27 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CartId', models.CharField(max_length=150)),
                ('Address', models.CharField(max_length=500)),
                ('State', models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('unsuccessful', 'Unsuccessful')], default='draft', max_length=150)),
                ('CustomerName', models.CharField(max_length=150)),
                ('phoneNumber', models.CharField(max_length=25)),
                ('UserId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryId', models.CharField(max_length=150)),
                ('Title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.CharField(db_index=True, max_length=150)),
                ('Price', models.FloatField(default=0)),
                ('DicountPer', models.FloatField(default=1)),
                ('Existance', models.BooleanField()),
                ('CategoryId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.categories')),
                ('UnitsId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.units')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.CharField(max_length=150)),
                ('ProductNumber', models.IntegerField(default=1)),
                ('total', models.FloatField()),
                ('ProductId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.products')),
            ],
        ),
    ]
